version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - express-server
    networks:
      - app-network
    image: skbarkat444/p5gapp-frontend:0.4

  express-server:
    build:
      context: .
      dockerfile: Dockerfile.express
    ports:
      - "3001:3001"
    networks:
      - app-network
    image: skbarkat444/p5gapp-backend:0.4

networks:
  app-network:
    driver: bridge

volumes:
  backend-volume: 
